purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.5194631768390536
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#1B1C21'
    - '#71706C'
    - '#42E1FE'
    - '#0077F7'
  rhythmicContrast: 0.2085106
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: ThisGayLife
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0.7978724
