purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0
  brandStrength: 0.5194631768390536
  lightness: 0
  brandColors:
    - '#0938A1'
    - '#FFFFFF'
    - '#B8C4E2'
    - '#018AB3'
    - '#684330'
  rhythmicContrast: 0.2085106
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: ThisGayLife
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0.7978724
